name: test CI

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]
  workflow_dispatch:

jobs:
  build-centos7:
    name: Build on centos
    runs-on: ubuntu-latest
    container:
        image: centos:7
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run build
      run: |
        echo "hello"
        cat /etc/os-release && pwd && ls
        echo $RUNNER_OS
        yum makecache && yum install -y gcc make
        make && ./hello

  build-fedora:
    name: Build on fedora
    runs-on: ubuntu-latest
    container:
        image: fedora:latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run build
      run: |
        echo "hello"
        cat /etc/os-release && pwd && ls
        echo $RUNNER_OS
        dnf makecache && dnf install -y gcc make
        make && ./hello

  build-ubuntu-22-04:
    name: Build on ubuntu-22-04
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run build
      run: |
        echo "hello"
        cat /etc/os-release && pwd && ls
        echo $RUNNER_OS
        sudo apt-get update && sudo apt-get install -y gcc make
        make && ./hello

  build-anolis:
    name: Build on anolis
    runs-on: ubuntu-latest
    container:
        image: openanolis/anolisos:8
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run build
      run: |
        echo "hello"
        cat /etc/os-release && pwd && ls
        echo $RUNNER_OS
        dnf makecache && dnf install -y gcc make
        make && ./hello